package au.edu.wehi.idsv;

import htsjdk.samtools.Cigar;
import htsjdk.samtools.CigarElement;

/**
 * Utility class to help handle unanchored reads generated by assembly of paired end reads.
 * 
 * Assemblies not including anchoring bases cannot be uniquely placed.
 * 
 * We use a placeholder CIGAR alignment of XNX to indicate the range of expected alignment locations for the assembly
 *
 */
public class UnanchoredReadUtil {
	public static int widthOfImprecision(final Cigar cigar) {
		if (cigar == null) return 0;
		// should only have XNX
		int width = 0;
		for (CigarElement ce : cigar.getCigarElements()) {
			switch (ce.getOperator()) {
			case X:
			case N:
				width += ce.getLength();
				break;
			case S:
			case H:
				break;
			default:
				// not in the correct format for an unanchored read
				return 0;
			}
		}
		return width;
	}
}
