library(StructuralVariantAnnotation)
library(argparser)
argp = arg_parser("Converts a VCF to a BED file containing breakpoint intervals. This is more complicated than just taking the VCF coordinates due to symbolic alleles (e.g. <DEL>) encoding their end position in the END attribute.")
argp = add_argument(argp, "--input", help="Input VCF containing structural variants.")
argp = add_argument(argp, "--output", help="BED file containing breakpoint positions.")
argv = parse_args(argp)

vcf = readVcf(argv$input)
bpgr = breakpointRanges(vcf, unpartneredBreakends=TRUE)
begr = breakpointRanges(vcf, unpartneredBreakends=FALSE)
remove(vcf)
gr = c(bpgr, begr)
remove(begr)
remove(bpgr)
sort(gr, ignore.strand=TRUE)
export(object=gr, con=argv$output, format="bed")
