package au.edu.wehi.idsv;

import htsjdk.samtools.Cigar;
import htsjdk.samtools.CigarElement;
import htsjdk.samtools.CigarOperator;
import htsjdk.samtools.SAMFileHeader;
import htsjdk.samtools.SAMFileWriter;
import htsjdk.samtools.SAMReadGroupRecord;
import htsjdk.samtools.SAMRecord;
import htsjdk.samtools.SAMRecordCoordinateComparator;
import htsjdk.samtools.SAMSequenceDictionary;
import htsjdk.samtools.SAMTag;
import htsjdk.samtools.SamPairUtil;
import htsjdk.samtools.metrics.Header;
import htsjdk.samtools.metrics.MetricsFile;
import htsjdk.samtools.reference.ReferenceSequenceFile;
import htsjdk.samtools.reference.ReferenceSequenceFileFactory;
import htsjdk.samtools.util.ProgressLoggerInterface;
import htsjdk.variant.variantcontext.VariantContext;
import htsjdk.variant.variantcontext.writer.VariantContextWriter;
import htsjdk.variant.vcf.VCFHeader;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;

import org.apache.commons.lang3.StringUtils;

import picard.analysis.InsertSizeMetrics;
import au.edu.wehi.idsv.debruijn.DeBruijnGraphBase;
import au.edu.wehi.idsv.debruijn.DeBruijnNodeBase;
import au.edu.wehi.idsv.debruijn.DeBruijnPathGraph;
import au.edu.wehi.idsv.debruijn.KmerEncodingHelper;
import au.edu.wehi.idsv.debruijn.PathNode;
import au.edu.wehi.idsv.debruijn.PathNodeBaseFactory;
import au.edu.wehi.idsv.debruijn.PathNodeFactory;
import au.edu.wehi.idsv.debruijn.ReadKmer;
import au.edu.wehi.idsv.debruijn.ReadKmerIterable;
import au.edu.wehi.idsv.debruijn.subgraph.DeBruijnReadGraph;
import au.edu.wehi.idsv.metrics.IdsvMetrics;
import au.edu.wehi.idsv.metrics.IdsvSamFileMetrics;
import au.edu.wehi.idsv.metrics.IdsvSamFileMetricsCollector;
import au.edu.wehi.idsv.metrics.InsertSizeDistribution;
import au.edu.wehi.idsv.metrics.SoftClipDetailMetrics;
import au.edu.wehi.idsv.metrics.SoftClipSizeDistribution;
import au.edu.wehi.idsv.sam.SAMRecordMateCoordinateComparator;
import au.edu.wehi.idsv.sam.SAMRecordUtil;
import au.edu.wehi.idsv.visualisation.NontrackingSubgraphTracker;

import com.google.common.collect.ImmutableList;
import com.google.common.collect.Lists;
import com.google.common.collect.Sets;

public class TestHelper {
	public static final BreakendDirection FWD = BreakendDirection.Forward;
	public static final BreakendDirection BWD = BreakendDirection.Backward;

	public static byte[] B(String s) {
		if (s == null)
			return null;
		return s.getBytes(StandardCharsets.US_ASCII);
	}
	
	public static byte[] B(byte b, int repeats) {
		byte[] result = new byte[repeats];
		for (int i = 0; i < result.length; i++) {
			result[i] = b;
		}
		return result;
	}
	
	public static byte[] B(int b, int repeats) {
		return B((byte)b, repeats);
	}

	public static String S(byte[] b) {
		if (b == null)
			return null;
		return new String(b, StandardCharsets.US_ASCII);
	}

	@SafeVarargs
	public static <T> List<T> L(T[]... list) {
		List<T> result = Lists.newArrayList();
		for (int i = 0; i < list.length; i++) {
			if (list[i] == null)
				continue;
			for (int j = 0; j < list[i].length; j++) {
				if (list[i][j] == null)
					continue;
				result.add(list[i][j]);
			}
		}
		return result;
	}

	@SafeVarargs
	static public <T> List<T> L(T... data) {
		List<T> list = Lists.newArrayList(data);
		return list;
	}

	public static IdsvVariantContextBuilder minimalVariant() {
		return (IdsvVariantContextBuilder) new IdsvVariantContextBuilder(
				getContext()).chr("polyA").start(1).stop(1).alleles("A", "C");
	}

	public static IdsvVariantContextBuilder minimalBreakend() {
		IdsvVariantContextBuilder builder = new IdsvVariantContextBuilder(
				getContext());
		builder.chr("polyA").start(1).stop(1).alleles("A", "A.");
		return builder;
	}

	static public SAMFileHeader getHeader() {
		SAMFileHeader header = new SAMFileHeader();
		header.setSequenceDictionary(getSequenceDictionary());
		SAMReadGroupRecord rg = new SAMReadGroupRecord("RG");
		rg.setSample("sample");
		header.addReadGroup(rg);
		return header;
	}

	static public SAMSequenceDictionary getSequenceDictionary() {
		return SMALL_FA.getSequenceDictionary();
	}

	static public byte[] GetPolyA(int length) {
		byte[] b = new byte[length];
		for (int i = 0; i < length; i++)
			b[i] = 'A';
		return b;
	}

	static public List<SAMRecord> sorted(List<SAMRecord> list) {
		List<SAMRecord> out = Lists.newArrayList(list);
		Collections.sort(out, new SAMRecordCoordinateComparator());
		return out;
	}

	static public List<SAMRecord> mateSorted(List<SAMRecord> list) {
		List<SAMRecord> out = Lists.newArrayList(list);
		Collections.sort(out, new SAMRecordMateCoordinateComparator());
		return out;
	}

	static public SAMRecord[] OEA(int referenceIndex, int pos, String cigar,
			boolean forward) {
		SAMRecord mapped = new SAMRecord(getHeader());
		mapped.setReferenceIndex(referenceIndex);
		mapped.setAlignmentStart(pos);
		mapped.setCigarString(cigar);
		mapped.setReadNegativeStrandFlag(!forward);
		mapped.setReadName(String.format("%s-%d-%d-%s", cigar, referenceIndex,
				pos, forward));
		mapped.setMappingQuality(10);
		mapped.setFirstOfPairFlag(true);
		mapped.setReadUnmappedFlag(false);
		clean(mapped);
		SAMRecord unmapped = Unmapped(mapped.getReadLength());
		unmapped.setSecondOfPairFlag(true);
		mapped.setReadUnmappedFlag(true);
		clean(mapped, unmapped);
		return new SAMRecord[] { mapped, unmapped };
	}

	public static NonReferenceReadPair NRRP(SAMRecord... pair) {
		NonReferenceReadPair rp = NRRP(SES(), pair);
		return rp;
	}

	public static NonReferenceReadPair NRRP(SAMEvidenceSource source,
			SAMRecord... pair) {
		pair[1].setReadName(pair[0].getReadName());
		return NonReferenceReadPair.create(pair[0], pair[1], source);
	}
	public SAMRecordAssemblyEvidence A(BreakpointSummary bs) {
		// TODO handle more cases
		assert(bs.start == bs.end);
		assert(bs.start2 == bs.end2);
		assert(bs.direction2 == BWD);
		SAMRecordAssemblyEvidence abe = AssemblyFactory.createAnchored(getContext(), AES(), bs.direction, Sets.<DirectedEvidence>newHashSet(
				SCE(bs)), bs.referenceIndex, bs.start, 1, B("TT"), B("TT"), 0, 0);
		SAMRecord r = new SAMRecord(getContext().getBasicSamHeader());
		r.setReferenceIndex(bs.referenceIndex2);
		r.setAlignmentStart(bs.start2);
		r.setReadUnmappedFlag(false);
		r.setCigar(new Cigar(ImmutableList.of(new CigarElement(2, CigarOperator.MATCH_OR_MISMATCH))));
		r.setMappingQuality(30);
		return AssemblyFactory.incorporateRealignment(getContext(), abe, r);
	}

	public static DirectedEvidence E(int referenceIndex, int start,
			BreakendDirection direction) {
		return new MockDirectedEvidence(referenceIndex, direction, start);
	}
	public static DirectedEvidence E(int referenceIndex, int start, int end,
			BreakendDirection direction) {
		return new MockDirectedEvidence(referenceIndex, direction, start, end);
	}

	public static SoftClipEvidence SCE(BreakendDirection direction,
			SAMRecord... pair) {
		return SCE(direction, SES(), pair);
	}
	private SoftClipEvidence SCE(BreakendSummary bs) {
		assert(bs.start == bs.end);
		if (bs.direction == FWD) {
			return SCE(bs.direction, Read(bs.referenceIndex, bs.start, "1M1S"));
		} else {
			return SCE(bs.direction, Read(bs.referenceIndex, bs.start, "1S1M"));
		}
	}

	public static SoftClipEvidence SCE(BreakendDirection direction,
			SAMEvidenceSource source, SAMRecord... pair) {
		if (pair.length >= 2) {
			return SoftClipEvidence.create(source, direction, pair[0],
					pair[1]);
		} else {
			return SoftClipEvidence.create(source, direction, pair[0],
					null);
		}
	}

	public static AssemblyEvidence AE() {
		return AssemblyFactory.createAnchored(getContext(), AES(),
				FWD,
				Sets.newHashSet((DirectedEvidence) SCE(FWD,
						Read(0, 1, "1M5S"))),
				0, 1,
				1, B("ATT"), new byte[] { 7, 7, 7 },
				6, 8);
	}
	public static class MockSoftClipSizeDistribution extends SoftClipSizeDistribution {
		public MockSoftClipSizeDistribution() {
			super(new ArrayList<SoftClipDetailMetrics>());
		}
		@Override
		public double getPhred(int softClipLength) {
			return softClipLength;
		}
	}

	public static class MockMetrics extends IdsvSamFileMetrics {
		public MockMetrics() {
			super(new InsertSizeMetrics(), new IdsvMetrics() {{
				MAX_READ_LENGTH = 100;
				MAX_PROPER_PAIR_FRAGMENT_LENGTH = 300;
				READ_PAIRS = 1000;
				READ_PAIRS_ONE_MAPPED = 25;
				READ_PAIRS_ZERO_MAPPED = 50;
				READ_PAIRS_BOTH_MAPPED = READ_PAIRS - READ_PAIRS_ONE_MAPPED - READ_PAIRS_ZERO_MAPPED;
				READS = 2 * READ_PAIRS;
				MAPPED_READS = READS - READ_PAIRS_ONE_MAPPED - 2*READ_PAIRS_ZERO_MAPPED;
			}}, new InsertSizeDistribution(
					new int[] { 1, 50, 100, 200, 300, 400, },
					new double[] { 1, 50, 500, 50, 20, 10, },
					1+50+500+50+20+10), new ArrayList<SoftClipDetailMetrics>());
		}
		@Override
		public SoftClipSizeDistribution getSoftClipDistribution() {
			return new MockSoftClipSizeDistribution();
		}
	}

	public static FileSystemContext getFSContext() {
		return new FileSystemContext(new File(
				System.getProperty("java.io.tmpdir")), 500000);
	}

	public static ProcessingContext getContext() {
		ProcessingContext pc = new ProcessingContext(getFSContext(),
				new ArrayList<Header>(), new SoftClipParameters(),
				new ReadPairParameters(), new AssemblyParameters() {{
					minReads = 2;
					assemble_remote_soft_clips = false;
					}},
				new RealignmentParameters(), new VariantCallingParameters(),
				SMALL_FA_FILE, false, false);
		return pc;
	}

	static public SAMRecord[] withReadName(String name, SAMRecord... data) {
		for (SAMRecord r : data) {
			r.setReadName(name);
		}
		return data;
	}

	static public SAMRecord[] withSequence(String seq, SAMRecord... data) {
		byte[] qual = B(seq);
		for (int i = 0; i < qual.length; i++) {
			qual[i] = 30;
		}
		return withSequence(seq, qual, data);
	}
	static public SAMRecord[] withSequence(String seq, byte[] qual, SAMRecord... data) {
		for (SAMRecord r : data) {
			r.setReadBases(B(seq));
			r.setBaseQualities(qual);
		}
		return data;
	}

	static public SAMRecord[] withSequence(byte[] seq, SAMRecord... data) {
		for (SAMRecord r : data) {
			r.setReadBases(seq);
		}
		return data;
	}

	static public SAMRecord[] withQual(byte[] seq, SAMRecord... data) {
		for (SAMRecord r : data) {
			r.setBaseQualities(seq);
		}
		return data;
	}

	static public SAMRecord[] withMapq(int mapq, SAMRecord... data) {
		for (SAMRecord r : data) {
			r.setMappingQuality(mapq);
		}
		return data;
	}
	
	static public SAMRecord[] withName(String readName, SAMRecord... data) {
		for (SAMRecord r : data) {
			r.setReadName(readName);
		}
		return data;
	}

	static public SAMRecord[] onNegative(SAMRecord... data) {
		for (SAMRecord r : data) {
			r.setReadNegativeStrandFlag(true);
		}
		return data;
	}

	public static SAMRecord[] withNM(SAMRecord... data) {
		for (SAMRecord r : data) {
			r.setAttribute("NM", null);
			SAMRecordUtil.ensureNmTag(SMALL_FA, r);
		}
		return data;
	}

	static public SAMRecord[] DP(int referenceIndex, int pos, String cigar,
			boolean forward, int referenceIndex2, int pos2, String cigar2,
			boolean forward2) {
		SAMRecord[] dp = new SAMRecord[] {
				OEA(referenceIndex, pos, cigar, forward)[0],
				OEA(referenceIndex2, pos2, cigar2, forward2)[0] };
		dp[0].setReadName(dp[0].getReadName() + "_" + dp[1].getReadName());
		dp[1].setReadName(dp[0].getReadName() + "_" + dp[1].getReadName());
		clean(dp[0], dp[1]);
		dp[0].setProperPairFlag(false);
		dp[1].setProperPairFlag(false);
		return dp;
	}
	static public SAMRecord Read(int referenceIndex, int pos, int length) {
		return Read(referenceIndex, pos, String.format("%dM", length));
	}

	static public SAMRecord Read(int referenceIndex, int pos, String cigar) {
		SAMRecord record = new SAMRecord(getHeader());
		record.setReadName(String
				.format("%s-%d-%d", cigar, referenceIndex, pos));
		record.setReferenceIndex(referenceIndex);
		record.setAlignmentStart(pos);
		record.setReadUnmappedFlag(false);
		record.setReadPairedFlag(false);
		record.setReadNegativeStrandFlag(false);
		record.setCigarString(cigar);
		record.setMappingQuality(10);
		clean(record);
		return record;
	}

	/**
	 * Read pair supporting the reference
	 * 
	 * @param referenceIndex
	 * @param pos
	 * @param readLength
	 * @return
	 */
	static public SAMRecord[] RP(int referenceIndex, int pos, int readLength) {
		return RP(referenceIndex, pos, pos + 2 * readLength, readLength);
	}

	/**
	 * Read pair supporting the reference
	 * 
	 * @param referenceIndex
	 * @param pos
	 *            start of first
	 * @param pos2
	 *            start of second
	 * @param readLength
	 *            read lengths
	 * @return read pair
	 */
	public static SAMRecord[] RP(int referenceIndex, int pos, int pos2,
			int readLength) {
		SAMRecord read1 = Read(referenceIndex, pos, readLength);
		SAMRecord read2 = Read(referenceIndex, pos2, readLength);
		read2.setReadNegativeStrandFlag(true);
		read1.setProperPairFlag(true);
		read2.setProperPairFlag(true);
		read1.setReadName(String.format("RP%d-%d:%d-%d", readLength, referenceIndex, pos, pos2));
		read1.setFirstOfPairFlag(true);
		read2.setFirstOfPairFlag(false);
		clean(read1, read2);
		return new SAMRecord[] { read1, read2 };
	}

	/**
	 * Fills in missing information from the given read
	 * 
	 * @param record
	 */
	public static void clean(SAMRecord record) {
		if (record.getHeader() == null) {
			record.setHeader(getHeader());
		}
		int cigarLength = record.getCigar() == null ? 0 : record.getCigar()
				.getReadLength();
		int readLength = record.getReadBases() == null ? 0 : record
				.getReadLength();
		int targetLength = cigarLength;
		if (targetLength == 0)
			targetLength = readLength;
		if (targetLength == 0)
			targetLength = 100;
		if (record.getReadBases() == null
				|| record.getReadBases().length != targetLength) {
			record.setReadBases(GetPolyA(targetLength));
		}
		if (record.getBaseQualities() == null
				|| record.getBaseQualities().length != targetLength) {
			byte[] quals = new byte[targetLength];
			Arrays.fill(quals, (byte) 10);
			record.setBaseQualities(quals);
		}
		if (record.getCigar() == null || record.getCigarLength() == 0) {
			record.setCigarString(String.format("%dM", targetLength));
		}
		if (!StringUtils.isNotBlank(record.getReadName())) {
			record.setReadName("placeholderReadName");
		}
		if (record.getReadGroup() == null) {
			record.setAttribute(SAMTag.RG.name(), getHeader().getReadGroups()
					.get(0).getId());
		}
		if (record.getReferenceIndex() != null
				&& record.getReferenceIndex() >= 0) {
			record.setReadUnmappedFlag(false);
		} else {
			record.setReadUnmappedFlag(true);
		}
		record.setAttribute("NM", 0);
		// if (record.getReadBases().length == targetLength)
		// SAMRecordUtil.ensureNmTag(SMALL_FA, record);
	}

	public static void clean(SAMRecord r1, SAMRecord r2) {
		clean(r1);
		clean(r2);
		r1.setFirstOfPairFlag(true);
		r2.setFirstOfPairFlag(false);
		r1.setSecondOfPairFlag(false);
		r2.setSecondOfPairFlag(true);
		r2.setReadName(r1.getReadName());
		r1.setReadPairedFlag(true);
		r2.setReadPairedFlag(true);
		if (r1.getFirstOfPairFlag() == r2.getFirstOfPairFlag()) {
			r1.setFirstOfPairFlag(true);
			r2.setFirstOfPairFlag(false);
		}
		boolean properpair = !r1.getReadUnmappedFlag()
				&& !r2.getReadUnmappedFlag()
				&& r1.getReferenceIndex() == r2.getReferenceIndex()
				&& r1.getReadNegativeStrandFlag() != r2
						.getReadNegativeStrandFlag();
		r1.setProperPairFlag(properpair);
		r2.setProperPairFlag(properpair);
		SamPairUtil.setMateInfo(r1, r2, getHeader());
	}

	public static File SMALL_FA_FILE = new File("src/test/resources/small.fa");
	public static ReferenceSequenceFile SMALL_FA = ReferenceSequenceFileFactory
			.getReferenceSequenceFile(new File("src/test/resources/small.fa"));
	public static final double DELTA = 1e-10;
	public static final byte[] POLY_A = B("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
	public static final byte[] POLY_ACGT = B("ACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGT");
	public static final byte[] RANDOM = B("CATTAATCGCAAGAGCGGGTTGTATTCGACGCCAAGTCAGCTGAAGCACCATTACCCGATCAAAACATATCAGAAATGATTGACGTATCACAAGCCGGATTTTGTTTACAGCCTGTCTTATATCCTGAATAACGCACCGCCTATTCGAACGGGCGAATCTACCTAGGTCGCTCAGAACCGGCACCCTTAACCATCCATATCCTTCAGTTCCATAGGCCTCTGTGCGGGATTTGTGAACGTTCGGACCCCCCAGGACAGCGTGCATGAGTTTCTAAACGCCCGGCCCCAACGGTCGTCCGGATGAATACTAGGCTAGGCATTGCGTTTACCTAGCTGCGTAAAATTTCGCTGATGGCGGGGATTCACACCACGCATTGTCTGAACACTTGTCTCTTTAGGTTCACTTTTGAGATATCATCAATCGAGAACGTTAGCATAATATCGGTCCTTAACGCCCGTAGCCCATTACAAGCCTCGAATTATGCACCTCCCAGGTACATATATTAGGGTTGTAACGCAAGTCATAATGGAAGCATCGCCGAAAGCGCACGCTGCTCAGTTTAGCACCATCGTCGGGCAAAGACATCCTGGACACGAGTGATAGGTCTTCGGATTGGGAGTCTCATACGCGTGCTAATGCTAACCGCACTGCTAATAATGGGTCCCCTATATGTAAGAACCGTTACGATACCTTCTGTCACAATCACACTGTGTGCAGAAGGGACTGGCTTATTTCCGTGGTCGCCCGGGCACAGTCTTCCACCAGCCGCCACGCCCGCTTGGTTCTCGTTGTCGGCGGTACTCGGGCCATTAGATTAATTTCAAATAATCGGCGGAGCGGGTCTGTGGGCCCTATTTGAAACCATCCTAGATTGTGTCTACTTAGGGAAACGGCCTGGGACTTCGTGATAGTAATGGATCCCCGAAGAAATCTATTTGTACTTACTGGGACTTTCCTCAATCTTCTCAAGAATGACAGCGTGCGGGACTGCTCATCCGAAGGAGGGGCGAGGGAAAACGACCCATCTTTGCTGGGGACAGGGCAGCTGCCACTAATATTGGTTTATGAATAGATTTAACAACCTTTCCAGGGTTGATATTGGCCGCTATTAAGTCATCAATCGAGTAAATTTAACCGTGGGACTCATTTGACTGCTCTTGGAAGCTCGACTACCTCGACGGCTAATGGGTTATCTCCCGACGTAAGGTCAACGGGGCCGGGCAATTCATTCCTAGCAATAAGGGATTCAATTTCTATACGTAAATGTGAGGAAGTAGACGTTACAGCGGGCATTTTAAGGCGACTTCTGGTTGTGGCCTGGCGAGACGACCTAGTTCGATAGACTTCCTGTCAAGACCAGTAAGCGTACTGTTTGTGCACCGGAACTGCGGCGAACGTAGCCGTAGCGCGGTACTTCGAATCGGAGACGGGCCGCAGGTACGTTGTTCAAAGCTGACAATAGAATATCGGGTGGCTCACACACACCAGAGGTAAATGCTACGTTTGACCGTCTCCGTACCATCCGTGATGGCTTCCTCCATAACTCGCCCTCTGTATGTAGCTATGATCTACGACGTGTTAGCCCTCTGCCTAAATGGGTGCAACAAGAACGCGGATGTCGTCCGGATGTCGACATTCCGGCCGGTCACACAAAGTAAAGCCAATAAGGAGTCTAAATCCTATCCACTGGCCCCTAGTGAAGGCCTGCACTTGGAGTAAGCGGACTGGCTATAATTTACAGGATAAGGGAAGCAAATAGGACAACGTCGATTAGCTAGACGTCGATAGGGATTGACACTCAGGTAGGTGTATGAAACGCTGTGTGGTGTTTGCCGAGCAAAACAGATTGCGACGTATGCGTATTTGCACCACCAATCCCAAGAAAAGGTAATGCTACGGGAAGCTAATATGACTGCCGTCGGGGGTGCTATGGAAGGCTCATACGCCAGGGTTGTCAACCTCTTGGACGTCCGAGGCCGCACGCAACTGGCAAGAAGAGTTCAATCCCGGCCCAGCTTTCCGCCTGCGAGGTATGGCACAGTGCAGTGATCCTAGGTATTAACAGGGGAGGAGAGACGATAGGTCCACTGCTGGGCCTGAGTTCTGATGATTTGGGCTCGCACTGATAATAGGGCTATTGGCCCTTCGTACTGATGGCAAATGACGCCCAATCGAAACTCCACCACACCAACCGAACCTCCTAAGAATGATTACAGCCTTGGAGATAGTGCGAACTGTTGGTCGTGTTCTCATCAACGCGTAGGTTCATTTGGGCAACATGGTCAGAGCGACGTCCCTAATTCTAATTTATAGAGAGCCCGGGAAATAATCTACTGGTTGACGCAGATTTTAATATCAGAGGGTACGTATTCAACGGAGGCGATCGGAACTTGGATCCCCGCATCTCCATACCCCCAAAAACCAGAACGAGCGTAAAAGGACTAGGTCAGAGTGGCCTACCGGTACAGCAACAGTGCGTTCACCTTAGCAAACCTGGAAACGCATGGTTTGAATAAAAATAGCTTTACTGACTGCGATAGAAAGTCGGCTTCGTTCCAACTGTGAGACAGTCGTGTCTCAGAGCAGAGGAGCTGAAGTGGGGAACCGGCGGCCATCACCGTCAGAAGGCCTTCCTCCTGTTTCATTTGGACGTTACTGGCACATCAAGCAATCCCCTGGAGGAGACCCTCGAGCCTAGTTGTCAATCAAATAACCCTACCGACTTCTATGTCTCGTGCGACCGTCGAAAATATGATTGCTTGCCACTAGACAGTCTGGCTGTTCGGCGATGTAACCAACTGTTAGAGAGGCGACAAGCCCTGATTGACCGTAGTGGTATGTGTTTTACACCCGTCGGGAAAGGGTTACGACACTGCGATGTTAAGGGCGCATCGCGACATTATTCGCTAGAACAGGTAACAACCATTAAATTGACTCTACCGGATAGCGCCGTTTCCTGTAATATATGTGCAGGAATGTCACCATGGGTGGTTCTCTCTACCTCCTCGATAAAGTACTGAGTGCTGCGGTGAGGAAACTGTTGTCCGTTCCAATCGACTGCCTACTGGGACATGCGTCTGCGGATTCCGGCATTCTCGTACCAGAGACCGGCGCATAGGAGAAATCCGCGACGATTCTCCGGAAGGCATGGGCTAACGGGGTATTCCTCTCTATATGACTCATCGTGCTCCAGCGTACCTCTGAGCCGATTGGTGCATCGGAGGACTGTCGATCCAACTGCTGCAGGGACTGAACTCTGTTCTCAGACCGGTACGTCTTGTATAAGTAGTCTCCCAGACTGGCGTGGTGTGCCGAACCCGTCGATCTGTTCAAAATTTCGCCTACCAGTCGCACGGACGTCACATTAGCTTAGACGGACGAATCTCCCAGTTATGCGTGATAGGGAGATAGGGCAGGCCGTGCGTCGCGTTGGACCGAGATGGCACGCCGCAAGGCAGCAGAAAGGGAAAAAGCGCCCGTGCCAACAGATCGATCAGTCCGTTTCCGAGGGTGCTTATTTTTAAGATATCCCTGGTTCTATGCCCAGGTAAGCGCGAGTACTGTCTTGTAGAGGACGTACAGGCATCTCTTACATGTGGAATTCCTGAGCACTTCTTGACGTCGTGTAACAACCGAAAGTATATTTAGCTCGGTAATTCATGTTCGGGTTATAATCAATTATCCTATTTTCAACGTATAGCAGCAACGGGGCCGGTGGTCCGCGTAGTGGATCGAAGCAGCCCTCTTGCTGACTTTAAGTACACGGCTAACGGTGGCTCGCGCCAAAACACTTTGTACGAGCTCGCAATCACCGGTCGCTGTATTTTGGGCCTAGTTTCCAGTGACCGAGAAGCTACCGTATACTATTGCACAAAGCGAAAGCATTTTGGTAGGTCAGCGGCTGCGATATCATAATGACCCGTATCTGAACGTCTCTGGACTTATAAATCTGAGAATCCATCTGCTAGCGACTCGCCTGGGAACAGGCTTTTTGTGCCATGCCTGATGCCATACTCCGAACACATGCCTAATTCGGCACCTATTAGCAACCCGGGGGCGATTTATAGTCCCCGCAGCCAAGTGAAGCAGCAACTCGACATGGAACTCGAGAAATCGGTACGGTATCACGACAGGTATTGGTATTGTCCACGATATCGATAGCCTATTTCGAAACCTGGTCCTTATAGGACGTGCTTCATATGTGCTTGCTCTCACTCTATTCGAAGCTCCACATACCGACCAGCTGTTTACTAAGTCAACCGCCAAATAGTCGCGGCGCTAGACACAAACTCCCTATAAAGGCAGGGATATGGAGCCAGCGCTACGAAAGGATTGCGTAGTTATTGCTCGGCCTTGTGACTGGCCGGACACAGATATGTCGTTCGCCTACGATAAGTGCGAACCAGGCCGTTGCAACCTTACGTTAATGCGGATACTGTTAAGCGTAATTGGACGAAATCCGGCGTAGGGTGCAGTTATCGACGTCGAAAAGCTCAGGGCGCGTAGTCCGATCTCGCTTAGGCCATCGGCTGGATTCGTGACGCGAACCGACCGGAACGGATGGAACTAGTACTTGGCCGTGTCATACGCATCGTCAAATCGTCTGATGTCGGGTGATGATGTGCGAACTACAGTCCTCCAGCGAAAAACAGTCTGAGCAAGCTTATGATGCTGATGGCACTGGATCCAAGGAAGGGTATTGCCGAAATTAATGACAGTCTCTGTAAAGGCCGACGACCCATTGTAAATTGTAACGCGTTTTCACGCTCCTGCTGTGTCGGGCCCCGGTCGGCTGTCGCCATGCCGACTCCTGGGTGGGCTACAATTGTAACATGCGGATAGGATCGCACTTCATAGAACACATTATAGTAATTTAACTTCCTGTTCCTGGAGGTAAGCGCGTCGCCTGATCTTGAGAGTCCCGTTCGTGAGAACCACAATTCACAGATTTGACGACTCCTTTTAATATAGCGACGGAGCACACCGCTCGTAATTCAGCTCGTAGTCTTTGCGTCTATCCACACACTCCCGGGCATATAGCTAACCGGACGCACAACTTACGGATCCTTACAACGTACAGCATTGGCACACGGAAGTTCCAGATGCTTCAATGGTACTTTCTTTTCAATTGGACAGGCTACGTAGCTAGTGCAATTGATATCAATGGGACATATGCTGAGAAAGCGACGGGGGCCGTGGGTTTTTTTGAGAGATGTAGCCGTACCCGGCCTGGATAGGCAGGCGCAATAGGAACGCAGGCAGCAATGCTTCGCAAATTGACAATATGCAGTGTCGCACTCGCGAGCAGCTCCTGGCGAGCTACGGATTAATTGTCATCTGAATTCAGGACGCAAGCCCGCTAAACCACGGGGTTCGGCACTAAGGACCATATTTATGCGACCGTTAGCTAATCGCCAGACGTTCGTGTCTTGGCGCGAATATAATATTCCCAGGGACTGTCGTTATACGATCTGGCCGGCATGAGACTTTACAAACTGTAGTTATTGGCCCACCGTTTACGCCGTGGTAATTTTGGGCAGGCTTGGAGAAGATTGAGATATAGCAGCGAACCACAGCGCCGGTCGATCGGACAAATTCTCCCTGTAAAGTGTTTATACCGTTTAGGAGATTGCGTAGGCACAGCAGCTTACGCCGATATGTCGAGGACACCCTTTCGATTATGAGCTCGTTCTAAGTATGCAGTAAAAGACCGATTGTTTTTCAGTAGGTGCATACCATAAAGGAAAGGGCGATTTACGTACACTCTACCTTTGATCCTAAAGACCTGGGTTCGTTGCAATGTCTTGTACCACATCCCCCATGAGGCTAACGTTATAGTCGACTATCGTCATCATCATTCTCTACGTATTGTTGCAATGGGACGAACGTGGACGCGTGTAAGAAACGCCAGTGTTGAGGTGTCCAGGAACAGGGAAAACCATAGTCTCGGCCGCTCGGTGTGGTACTTGCAAAACAAAAAAGGTGTTAGTCGCGCAGTTACACCTGGCTGTATTCGTCAACCACGACATAAGGGCGTAGTGACGATTAAGTGTTAGGCTATGTGGTGAATCTGCGTGTGGTGGCACGGTATAAGCCGGATAGCAATAGACCCCACTATAGACTTAGTAGTTTTGCCCTGAATAACTCCGGGGAATGCAAGATCAGAAAAAACCTTCAGCGATCATATGAGGTTGCAGTATGGTACGGATGGGGTCCAGTCTTGAAAAAATAAGGTTATCCCCAATCTGCCGGTCAAATAGTTAACCGCCCTTCCCTATGCACCAACTTTTTTAGGATCGGCTCGGTTCCAATTAATATGTGTGGGGCTAGCCTCGCACGTCGGCCACAGCGAAAAGAATATCGAGATTTTGGAACGTGCCCAAGCATCCATAATAGTCCTTGATCTTCCAACCAGACAGCGATGCTCGAACCGGTCCCCAAATAGAATGACTAAACGGACGAAGAGAGGTTTCAATCACTCCTCTGTGGGCCGATCACGATTACAGTTAGCACCAGCGTTCGATCTCCTCTAGAGAACCCACACGCGATCCTCATATTGGTGGGGCCAATGATACTAAGCTCAGGTCCCTAATGATACCTCCATCGCTATACGCGTTTGGTGTAACCAGATTTTCCCGGCGGGACTACCTCACTGGTTTTCGGCGGTGCAGCCTTTGTGTTCGAGGTACGCGCCGACCGCAAGCCCCCGCGCCCGTACAAAACTTCGTCTGTTCAATAACAGCGGCGTTAAGCTAACGGCGAGAAATCTCTCACTTCCCGTCCAAAGGAAGACCTGAAGTCATAATCTTGCAACACCGAAGAACTGGCTAATGGGTTGTAAGATATGCTATTCATATGGTAGGAAGGTTCGCAAGAGATTTTAGAGGGTCTGTCTAGCCAGGAACCCCAGCGACTATGTTCTTCTCCGCATCGGCCCAACCACCTGGCAATTTCCCAATTCTAGTAACTCATCCAAACACCCTTCTCATAAGTGCAAGGTCTCAATACACAAGTCGAAATGTGGGGGGCTACGGCCCTACGTCTAGTTAGTTGGGCGAGTCTTCTATATGGACTCATAGTGTGGAACTATAGGCACATGGGTCCTATTCAAATAGCAGCTGATAGAGACATGTTACGGTGAGGTCCGCTGCATTAGCGGGAACCGCAATTATCATACTTGGCCTATTTGTCAGCTTGGCTAGCGTTTGCAGGCCATGTAAAGGATTGCATGTTCTACTCAGTTGGTCTGCCCCAATCGTTAGGCGCTGGGGCTGAAATTATTCCCGATAGTATTATTCGTGGTAGCGTGTTAGTAGCAAGATTGGGTAATACGATCTGAGCTCGGGTGATTCTGCTATCAAATGTGGGACTTAAGATTTTCTCAACGGCTGACGGCCGCCTGAGTGTGTCCCTGGTCCAAGATAGGGTCTCAGCAAACTCAAAGACGGGGAGCCTAGTTACGGTGGTATTAGAGATCGACAGAGAATGGAGGAGAACTATCGTTAACCTGTCGTGCGCAAGTTGGGACCGATAGAGTAGCTAGTAATAATATGGACCTTGCTTATTCATCTGCGTAGCATTATGCTGTAAATCTATACGTCCTTCTTCGGGAGTTACTTCCAGATCCAAATTGAACAATATTACCCGAGTTGGACTCGGTGCGCGGGTGACGGATAGACAGCAACGCAAATTAAATACCCAGTGTGTACGAGGTGCTCCTATGCGGCCCCTCGAGGGGCTAGGTGCTCGCGCCTTAACCCCACTTAAGGGGGACCCCAAGCCAGGCCTCTCGTCGTACTAACTTTATATTCCGCGTGCTTGCTCTTCCGTCTTTGCTTGAACCATCCGGGTGGATGAAGATTGCAAGGAGTTTATACTGTAAGGAGGCCTCAAATCTTCAAGTTTAGCATCACCCGCCCTACCAACTGCTCATATCAGCTCGCCGGAGGCCTCGAAGACCTCCTCTCAATGATAGGAGATCGCGTACCAGATGAACTCTACGCTAACAAGGGTCACCGACCAACGCCCTTAGGAGCAATCACATCACCTGTTCCATCATGCATCTAATGAACACGCGAGGCTGTCGAGAGGCACCACGAACGGCAAACTAGATAGAAGATTCAACAGCCGGTCTAACGCGCCAACGCACCGTTGTGACGTTGGGTTCGCATTGATAAGCGTTGACTTTCCAGTCTGGGGGCATAAATGAATATACGGATAAGGCGTTCAATGCAGGCAATTGGCTCCGCGAGTAGTCTGTGCCTCGTCAATCTTTTTCTGGTCTCACGTTGTCTCGATCCGATATACTCTTGAGCACACCATAGAACTACAACTAACGGGCGGCGTTATTTGAGTTAGAGAGCTTCGGGGATACTTATTCAGGTACGGTCTGTCTTCGGGAGTGTGACAGTACATGAATTAGCCTTGGTAGCAAGACAATTTTGTGAATATGCGGACAGTCAGGTAATCCCCCCATAATAGTTGCGAGATCCTCAGGCACTCGAGTGCGAGCCAGGGGAGAGGACCCTGGTGGAATATCCTCCAGTGTTCAGCTACTTCTCGCCCGCCGCGATAACACTGCGAGTGGGGCACCAGGTCTCACTCCCTGGGTATGCAGTTTCTAATGCATTAGAGGGTGCTGCGGTCCTACCCGCCAATAAGGCGTTAGGCTTAATGTTACGTGAGCTGCACCACACTGCCGTGCTCACAAAGGCCGTGATATTGGATCATTCCTGCTACGGCATCGATAGAAGAGTGAATACGGTATCCAAAAACATCTATTTATACGAGCATCCGAATGCCCCTGACCTGACATTGTCACTACGACAGCTCTTTCGGGTAATAACGCTTTTGCCTTTGCCTTTAACGTGCTGTATTTACGGCCCTTAGTGAGCCATCCACGGAAGGTCGCTTCCATATCAATGTCATAGAAAGCAAACATTGGGGAACAAGACGCTGATTCGCCTAGTGATTAGCGTGCTGCCGGCTGGGGCTTTTTTAATCTTCCTCGGCCACCCGATTATACGAAGTTAGGAATGGCGTGGTCGTACCCCGCCATCCTACCATAAAGCACAATATATCGTCTTTCGGAGTCAGGTCGAGGGGGTAGGGCCAGTTTTAGTTAGTGGATCCGTCACAACGTATCAGTGCCTGCGTCTACTGTGGTGTGGCTAAGATTAATAGCCTTGAGATCCCTTCTTCAGACACGCACAGCCAGTGGTCCTGTGTTCCATGACAGTGCTCGGGGGACCGTGGGCTAGTGCGGCGCGACCTGTATACGTTGACCTTGGCATCGTCTGAATGGCGGCCTGTTCAGTGTATGGGTGCCTTAACCATAGTTTGTAGGACTGTCCGGTCTGGGTAGGGTGCTCTGTTAGGCCATTTCCTCTTTGTTACATTCTGTCCTATCCACCCGCCAAAGGGCGTGAAAGAATCCTTTGTGAACCGGTTATCGCGAGCCCAGATCTCCATAGCGGGAGCGCGCTGAAGCACAACTCGTATCATGAGGAAGATCCGGGTAGAAAAAAGAACTCGAGTGAGCAAGTAGTATACTCAAGCCTCGTGGTATCAGCAATTAGGATGTTTATCATTGTCTGACACTAACCCCACAAGCAAACGTTTCGACATGTTGCCAGCAGGGCTAGCGCATACCTATTCATTACATGCACTTCTCGGAGTCTCCCCCTCCCAGTTCGTGTGCGCACCGGCCGATACATATCCATCGGGATTCGTAAAAGGGGACTAAAAGAACGCAAATTAGAGAACAAAATAACCCCCAGAGCGCTGTAAAACATAGTAAATTCTACTCGCTCAACTTGGGTTATACCCGTAGCTAAGTTCCCGTGATGTTGGGGACGCTTTGAAATAGTCCTCGAGGGTGAAACGTACCCTTAGGGCCTGTACACATTCTCTGTGTCGACTAGTTGCCACGTCTAAATTGGGCATACGATCACGGGTACAGGTGGCATAAGTATAACTGGGCTTCCGAGACCGCACGTG");
	public static final byte[] NPOWER2 = B("NNANAAANAAAAAAANAAAAAAAAAAAAAAANAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");

	public static class StubSAMFileWriter implements SAMFileWriter {
		public StubSAMFileWriter() {
			this(new SAMFileHeader());
		}

		public StubSAMFileWriter(SAMFileHeader header) {
			this.header = header;
			this.header.addReadGroup(new SAMReadGroupRecord("RG"));
		}

		public StubSAMFileWriter(ReferenceSequenceFile reference) {
			this();
			this.header
					.setSequenceDictionary(reference.getSequenceDictionary());
		}

		public SAMFileHeader header;
		public ArrayList<SAMRecord> list = new ArrayList<SAMRecord>();

		@Override
		public void addAlignment(SAMRecord alignment) {
			list.add(alignment);
		}

		@Override
		public SAMFileHeader getFileHeader() {
			return header;
		}

		@Override
		public void close() {
			closed = true;
		}

		public boolean closed;

		@Override
		public void setProgressLogger(ProgressLoggerInterface progress) {
		}
	}

	public static class StubVariantContextWriter implements
			VariantContextWriter {
		public VCFHeader header = null;
		public ArrayList<VariantContext> data = new ArrayList<VariantContext>();

		@Override
		public void writeHeader(VCFHeader header) {
			this.header = header;
		}

		@Override
		public void close() {
		}

		@Override
		public void add(VariantContext vc) {
			this.data.add(vc);
		}
	}

	static public SAMRecord Unmapped(int readLength) {
		SAMRecord record = new SAMRecord(getHeader());
		record.setReadUnmappedFlag(true);
		record.setAlignmentStart(SAMRecord.NO_ALIGNMENT_START);
		record.setReferenceIndex(SAMRecord.NO_ALIGNMENT_REFERENCE_INDEX);
		record.setMappingQuality(SAMRecord.NO_MAPPING_QUALITY);
		record.setCigarString(SAMRecord.NO_ALIGNMENT_CIGAR);
		record.setReadBases(GetPolyA(readLength));
		return record;
	}

	// -------- Path graph helpers --------
	public static class BaseGraph extends DeBruijnGraphBase<DeBruijnNodeBase> {
		public BaseGraph(int k) {
			super(k);
		}

		@Override
		protected DeBruijnNodeBase merge(DeBruijnNodeBase node,
				DeBruijnNodeBase toAdd) {
			node.add(toAdd);
			return node;
		}

		@Override
		protected DeBruijnNodeBase remove(DeBruijnNodeBase node,
				DeBruijnNodeBase toRemove) {
			throw new RuntimeException("NYI");
		}

		public BaseGraph add(String sequence) {
			return add(sequence, 1);
		}

		public BaseGraph add(String sequence, int weight) {
			for (long kmer : toKmer(this, sequence)) {
				add(kmer,
						new DeBruijnNodeBase(weight, NRRP(OEA(0, 1, "100M",
								true))));
			}
			return this;
		}

		public String S(PathNode<DeBruijnNodeBase> node) {
			return new String(getBaseCalls(node.getPath()));
		}
	}

	public static class BasePathGraph extends
			DeBruijnPathGraph<DeBruijnNodeBase, PathNode<DeBruijnNodeBase>> {
		public BasePathGraph(
				BaseGraph graph,
				long seed,
				PathNodeFactory<DeBruijnNodeBase, PathNode<DeBruijnNodeBase>> factory) {
			super(graph, seed, factory, new NontrackingSubgraphTracker());
		}

		public BasePathGraph(BaseGraph g, PathNodeBaseFactory factory) {
			super(g, factory, new NontrackingSubgraphTracker());
		}

		public PathNode<DeBruijnNodeBase> get(String kmer) {
			assert (kmer.length() == getGraph().getK());
			long state = KmerEncodingHelper.picardBaseToEncoded(getGraph()
					.getK(), B(kmer.substring(0, getGraph().getK())));
			for (PathNode<DeBruijnNodeBase> n : getPaths()) {
				for (List<Long> kmers : n.getPathAllKmers()) {
					if (kmers.contains(state))
						return n;
				}
			}
			return null;
		}

		public PathNode<DeBruijnNodeBase> addNode(String sequence) {
			return addNode(sequence, 1);
		}

		public PathNode<DeBruijnNodeBase> addNode(String sequence,
				int kmerWeight) {
			((BaseGraph) getGraph()).add(sequence, kmerWeight);
			PathNode<DeBruijnNodeBase> n = new PathNode<DeBruijnNodeBase>(
					toKmer(getGraph(), sequence), getGraph());
			super.expectedWeight += n.getWeight();
			return n;
		}

		public String S(PathNode<DeBruijnNodeBase> node) {
			return new String(getGraph().getBaseCalls(node.getPath()));
		}

		public String S(Iterable<PathNode<DeBruijnNodeBase>> nodes) {
			return new String(getGraph().getBaseCalls(
					Lists.newArrayList((PathNode.kmerIterator(nodes)))));
		}
	}

	public static <T extends DeBruijnNodeBase> String S(DeBruijnGraphBase<T> g,
			Iterable<Long> path) {
		return new String(g.getBaseCalls(Lists.newArrayList(path)));
	}

	public static List<Long> toKmer(DeBruijnGraphBase<DeBruijnNodeBase> graph,
			String sequence) {
		assert (sequence.length() >= graph.getK());
		byte[] qual = new byte[sequence.length()];
		Arrays.fill(qual, (byte) 1);
		List<Long> result = Lists.newArrayList();
		for (ReadKmer rk : new ReadKmerIterable(graph.getK(), B(sequence),
				qual, false, false)) {
			result.add(rk.kmer);
		}
		return result;
	}

	public static <T extends DeBruijnNodeBase, PN extends PathNode<T>> PN PGN(
			DeBruijnPathGraph<T, PN> pg, String sequence) {
		assert (sequence.length() == pg.getGraph().getK());
		long state = KmerEncodingHelper.picardBaseToEncoded(pg.getGraph()
				.getK(), B(sequence));
		for (PN n : pg.getPaths()) {
			for (List<Long> kmers : n.getPathAllKmers()) {
				if (kmers.contains(state))
					return n;
			}
		}
		return null;
	}

	public static BaseGraph G(int k) {
		return new BaseGraph(k);
	}

	public static BasePathGraph PG(BaseGraph g, String seed) {
		return new BasePathGraph(g, KmerEncodingHelper.picardBaseToEncoded(
				g.getK(), B(seed)), new PathNodeBaseFactory());
	}

	public static BasePathGraph PG(BaseGraph g) {
		return new BasePathGraph(g, new PathNodeBaseFactory());
	}

	public static DeBruijnReadGraph G(int k, BreakendDirection direction) {
		AssemblyParameters p = new AssemblyParameters();
		p.k = k;
		return new DeBruijnReadGraph(getContext(), AES(), 0, direction, p, null);
	}

	public static class MockSAMEvidenceSource extends SAMEvidenceSource {
		public IdsvSamFileMetrics metrics = new MockMetrics();
		public boolean isTumour = false;

		public MockSAMEvidenceSource(ProcessingContext processContext) {
			super(processContext, new File("test.bam"), false);
		}
		protected MockSAMEvidenceSource(ProcessingContext processContext, int minFragmentSize, int maxFragmentSize) {
			super(processContext, new File("test.bam"), false, minFragmentSize, maxFragmentSize);
			metrics.getIdsvMetrics().MAX_PROPER_PAIR_FRAGMENT_LENGTH = maxFragmentSize;
			metrics.getIdsvMetrics().MAX_READ_LENGTH = maxFragmentSize;
		}
		@Override
		public boolean isTumour() {
			return isTumour;
		}
		@Override
		public boolean isComplete(ProcessStep step) {
			if (step == ProcessStep.CALCULATE_METRICS) return true;
			return super.isComplete(step);
		}
		@Override
		protected IdsvSamFileMetrics getMetrics() {
			if (metrics != null) return metrics;
			return super.getMetrics();
		}
	}

	public static MockSAMEvidenceSource SES() {
		return new MockSAMEvidenceSource(getContext());
	}
	public static MockSAMEvidenceSource SES(ProcessingContext context) {
		return new MockSAMEvidenceSource(context);
	}
	public static MockSAMEvidenceSource SES(boolean isTumour) {
		MockSAMEvidenceSource e = new MockSAMEvidenceSource(getContext());
		e.isTumour = isTumour;
		return e;
	}
	public static MockSAMEvidenceSource SES(int maxFragmentSize) {
		return (SES(0, maxFragmentSize));
	}
	public static MockSAMEvidenceSource SES(int minFragmentSize, int maxFragmentSize) {
		return new MockSAMEvidenceSource(getContext(), minFragmentSize, maxFragmentSize);
	}
	public static AssemblyEvidenceSource AES() {
		return new AssemblyEvidenceSource(getContext(),
				ImmutableList.<SAMEvidenceSource>of(SES()), new File(
						"test.bam"));
	}
	public static AssemblyEvidenceSource AES(ProcessingContext context) {
		return new AssemblyEvidenceSource(context,
				ImmutableList.<SAMEvidenceSource>of(SES(context)), new File(
						"test.bam"));
	}
	public static AssemblyEvidenceSource AES(int maxFragmentSize) {
		return new AssemblyEvidenceSource(getContext(),
				ImmutableList.<SAMEvidenceSource>of(SES(maxFragmentSize)), new File(
						"test.bam"));
	}
	public VariantContextDirectedEvidence CallSV(DirectedEvidence... evidence) {
		IdsvVariantContextBuilder vcBuilder = new IdsvVariantContextBuilder(getContext());
		byte[] seq = evidence[0].getBreakendSequence();
		vcBuilder.breakend(evidence[0].getBreakendSummary(), seq == null ? "" : new String(seq, StandardCharsets.US_ASCII));
		StructuralVariationCallBuilder builder = new StructuralVariationCallBuilder(getContext(), (VariantContextDirectedEvidence)vcBuilder.make());
		for (DirectedEvidence e : evidence) {
			builder.addEvidence(e);
		}
		return builder.make();
	}
	public IdsvMetrics IDSV(Collection<SAMRecord> input) {
		IdsvSamFileMetricsCollector c = new IdsvSamFileMetricsCollector(null);
		for (SAMRecord r : input) {
			c.acceptRecord(r, null);
		}
		MetricsFile<IdsvMetrics, Integer> idsv = new MetricsFile<IdsvMetrics, Integer>();
		MetricsFile<InsertSizeMetrics, Integer> is = new MetricsFile<InsertSizeMetrics, Integer>();
		MetricsFile<SoftClipDetailMetrics, Integer> sc = new MetricsFile<SoftClipDetailMetrics, Integer>();
		c.finish(is, idsv, sc);
		IdsvMetrics metrics = idsv.getMetrics().get(0);
		return metrics;
	}
}
