package au.edu.wehi.socrates;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;

import picard.cmdline.Option;
import picard.cmdline.StandardOptionDefinitions;
import picard.cmdline.Usage;
import htsjdk.samtools.util.IOUtil;
import htsjdk.samtools.reference.ReferenceSequenceFile;
import htsjdk.samtools.reference.ReferenceSequenceFileFactory;
import htsjdk.samtools.util.CloseableIterator;
import htsjdk.samtools.util.Log;
import htsjdk.samtools.util.ProgressLogger;
import htsjdk.samtools.SAMFileHeader;
import htsjdk.samtools.SAMRecord;
import htsjdk.samtools.SAMSequenceDictionary;
import htsjdk.samtools.SAMSequenceRecord;
import htsjdk.samtools.SamReader;
import htsjdk.samtools.SamReaderFactory;
import htsjdk.variant.variantcontext.VariantContext;
import htsjdk.variant.variantcontext.writer.VariantContextWriter;
import htsjdk.variant.variantcontext.writer.VariantContextWriterBuilder;
import htsjdk.variant.vcf.VCFFileReader;
import htsjdk.variant.vcf.VCFHeader;

import com.google.common.collect.Iterators;
import com.google.common.collect.Lists;
import com.google.common.collect.PeekingIterator;
import com.sun.tools.javac.util.List;

import au.edu.wehi.socrates.vcf.VcfConstants;

/**
 * Clusters evidence that supports a common breakpoint together
 * @author Daniel Cameron
 *
 */
public class AnnotateBreakends extends CommandLineProgram {

    private static final String PROGRAM_VERSION = "0.1";

    // The following attributes define the command-line arguments
    @Usage
    public String USAGE = getStandardUsagePreamble() + "Annotates breakend calls with supporting evidence "
    		+ PROGRAM_VERSION;
    @Option(doc = "Input BAM file.",
            optional = false,
            shortName = StandardOptionDefinitions.INPUT_SHORT_NAME)
    public File INPUT;
    @Option(doc = "Breakpoint calls in VCF format",
            optional = true,
            shortName= StandardOptionDefinitions.OUTPUT_SHORT_NAME)
    public File OUTPUT;
    @Option(doc="Reference used for alignment",
    		optional = false,
    		shortName=StandardOptionDefinitions.REFERENCE_SHORT_NAME)
    public File REFERENCE;
    @Option(doc = "Picard metrics file generated by ExtractEvidence",
            optional = true)
    public File METRICS = null;
    private Log log = Log.getInstance(AnnotateBreakends.class);
    @Override
	protected int doWork() {
    	try {
    		if (METRICS == null) {
    			METRICS = FileNamingConvention.getMetrics(INPUT);
    		}
    		if (OUTPUT == null) {
    			OUTPUT = FileNamingConvention.getOutputVcf(INPUT);
    		}
    		IOUtil.assertFileIsReadable(INPUT);
    		IOUtil.assertFileIsReadable(REFERENCE);
    		IOUtil.assertFileIsReadable(METRICS);
    		IOUtil.assertFileIsWritable(OUTPUT);
    		
    		
	    	final RelevantMetrics metrics = new RelevantMetrics(METRICS);
	    	final ReferenceSequenceFile reference = ReferenceSequenceFileFactory.getReferenceSequenceFile(REFERENCE);
	    	final SAMSequenceDictionary dictionary = reference.getSequenceDictionary();
	    	final ProcessingContext processContext = new ProcessingContext(reference, dictionary, metrics);
    		
    		final SamReader inputReader = getSamReaderFactory().open(INPUT);
    		final CloseableIterator<SAMRecord> inputIterator = inputReader.iterator(); 
    		SequentialReferenceCoverageLookup referenceLookup = new SequentialReferenceCoverageLookup(3 * metrics.getMaxFragmentSize(), inputIterator);
    		final Iterator<SAMRecord> allReads;
    		final Iterator<DirectedEvidence> evidenceIt = getAllEvidence(processContext);
    		final Iterator<VariantContextDirectedBreakpoint> toAnnotateIt = getCallsToAnnotate();
    		// For each breakend
    			// Get all DirectedEvidence for breakend
    			// Get reference evidence
    			// annotate call with evidence
    				// including setting untemplated sequence
    			// write annotated call
    		inputIterator.close();
    		
    	} catch (IOException e) {
    		log.error(e);
    		throw new RuntimeException(e);
    	}
        return 0;
    }
	private Iterator<DirectedEvidence> getAllEvidence(final ProcessingContext processContext) throws IOException {
		if (FileNamingConvention.getSVBam(INPUT).exists()) {
			log.info("Using combined files for SV evidence");
			final DirectedEvidenceFileIterator dei = new DirectedEvidenceFileIterator(
					processContext,
					getSamReaderFactory(),
					ensureFileExists(FileNamingConvention.getSVBam(INPUT)),
					ensureFileExists(FileNamingConvention.getMateBam(INPUT)),
					ensureFileExists(FileNamingConvention.getRealignmentBam(INPUT)),
					ensureFileExists(FileNamingConvention.getBreakendVcf(INPUT)));
			return dei;
		} else {
			log.info("Using per chromosome files for SV evidence");
			ArrayList<Iterator<DirectedEvidence>> itList = new ArrayList<Iterator<DirectedEvidence>>();
			for (SAMSequenceRecord seq : processContext.getDictionary().getSequences()) {
				String chr = seq.getSequenceName();
				itList.add(new DirectedEvidenceFileIterator(
						processContext,
						getSamReaderFactory(),
						ensureFileExists(FileNamingConvention.getSVBamForChr(INPUT, chr)),
						ensureFileExists(FileNamingConvention.getMateBamForChr(INPUT, chr)),
						ensureFileExists(FileNamingConvention.getRealignmentBamForChr(INPUT, chr)),
						ensureFileExists(FileNamingConvention.getBreakendVcfForChr(INPUT, chr))));
			}
			return Iterators.concat(itList.iterator());
		}
	}
	private Iterator<VariantContextDirectedBreakpoint> getCallsToAnnotate() throws IOException {
		// open VCF
		// (assert sorted?)
		if (FileNamingConvention.getRawCallVcf(INPUT).exists()) {
			log.info("Using single breakpoint vcf call file ", FileNamingConvention.getRawCallVcf(INPUT));
			VCFFileReader reader = new VCFFileReader(FileNamingConvention.getRawCallVcf(INPUT));
			return reader.iterator();
		} else {
			log.info("Using per chromosome paired breakpoint vcf call file ", FileNamingConvention.getBreakpointVcf(INPUT));
			OUTPUT = FileNamingConvention.getRawCallVcf(INPUT, CHROMSOME[0], CHROMSOME[1]);
			Iterators.mergeSorted()
			
			log.info("Sorting breakends for chr in memory");
			
			// Merge calls for (chrA, chrB) for A<B
			// also need to all B>A
			
			// it = Iterators.concat(it, new);
		}
		throw new RuntimeException("NYI");
	}
	public static void main(String[] argv) {
        System.exit(new GenerateDirectedBreakpoints().instanceMain(argv));
    }
}