################## BASE IMAGE ######################

FROM biocontainers/biocontainers:latest

################## METADATA ######################
LABEL base.image="biocontainers:latest" 
LABEL version="1"
LABEL software="GRIDSS"
LABEL software.version="1.7.2"
LABEL about.summary="Genomic Rearrangement IDentification Software Suite"
LABEL about.home="https://github.com/PapenfussLab/gridss"
LABEL about.documentation="https://github.com/PapenfussLab/gridss"
LABEL license="https://github.com/PapenfussLab/gridss"
LABEL about.tags="Genomics"

################## MAINTAINER ######################
MAINTAINER Daniel L Cameron <daniel.l.cameron@gmail.com>

USER biodocker

RUN conda install bwa java-jdk picard r-base samtools 

WORKDIR /home/biodocker/bin/

RUN wget https://github.com/PapenfussLab/gridss/releases/download/v1.7.2/gridss-1.7.2-gridss-jar-with-dependencies.jar

WORKDIR /data/

ENTRYPOINT ["java", "-ea", "-Xmx31g", "-Dsamjdk.create_index=true", "-Dsamjdk.use_async_io_read_samtools=true", "-Dsamjdk.use_async_io_write_samtools=true", "-Dsamjdk.use_async_io_write_tribble=true", "-Dgridss.gridss.output_to_temp_file=true", "-Dgridss.keepTempFiles=true", "-cp", "/home/biodocker/bin/gridss-1.7.2-gridss-jar-with-dependencies.jar", "gridss.CallVariants", "TMP_DIR=.", "WORKING_DIR=."]